### ISSUE TITLE
[v0.13] Release Tracker

### ISSUE THREAD

**Issue by Nayef211** [pytorch/text#1766]
We cut a [release branch](https://github.com/pytorch/text/tree/release/0.13) for the 0.13 release. (common commit  with main is d6e3550)

This issue is for tracking cherry-picks to the release branch.
The POCs for the TorchText team are @Nayef211 and @VirgileHlav

### Versions

0.13

### Cherry-Pick (until 06/13/22)
We will keep cherry-picking all PRs landed to main branch until PyTorch 1.12.0 official released.
When you add PR against release branch, please link the landed PR from main branch.

RC-release can be found in https://download.pytorch.org/whl/test/cpu/torch_test.html

### Cherry-Picked PRs

- [x] https://github.com/pytorch/text/pull/1768
- [x] https://github.com/pytorch/text/pull/1772
- [x] https://github.com/pytorch/text/pull/1774
- [x] https://github.com/pytorch/text/pull/1784
- [x] https://github.com/pytorch/text/pull/1785
- [x] https://github.com/pytorch/text/pull/1786
- [x] https://github.com/pytorch/text/pull/1788
- [x] https://github.com/pytorch/text/pull/1791

### TO DO
- [x] https://github.com/pytorch/text/pull/1802

**Comment by atalman** [comment]
Cherry pick PR: https://github.com/pytorch/text/pull/1784
Critical CI Fixses

**Comment by atalman** [comment]
Cherry pick PR: https://github.com/pytorch/text/pull/1784
Critical CI Fixes

---
@atalman merged

**Comment by atalman** [comment]
Cherry pick PR: https://github.com/pytorch/text/pull/1786
Critical CI Fixes

---
@atalman merged

**Comment by parmeet** [comment]
cherry pick PR #1788 
Doc Fix

**Comment by Nayef211** [comment]
Closing out the issue as torchtext 0.13.0 is officially available on [PyPi](https://pypi.org/project/torchtext/) and [conda](https://anaconda.org/pytorch/torchtext). You can view the release notes [here](https://github.com/pytorch/text/releases/tag/v0.13.0).
